### ISSUE TITLE
Publishers in Python Nodes Should Be Asyncronous

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#284]
swri_transfrom_util initializat_origin.py needs to be updated for this.

See http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers#queue_size:_publish.28.29_behavior_and_queuing

**Comment by pjreed** [comment]
Both of the publishers in there look to me like they're already being initialized with a queue_size, which, according to the documentation, should make them asynchronous.  Are you seeing different behavior?

**Comment by evenator** [comment]
It looks like @elliotjo sneakily fixed it in 407916b14ba4c7d551987cfc1e47185b39cbb7b1
