### ISSUE TITLE
Jade Fails to Build Due to Eigen3 Rosdep Error

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#296]
From @pjreed:
> Jade branch is failing to build due to swri_geometry_util (and possibly others) being unable to find "Eigen3".

**Comment by pjreed** [comment]
The dependency probably just needs to be changed from "Eigen3" to "Eigen", but I don't actually have a Jade install to test it with.

**Comment by pjreed** [comment]
I tested compiling it in a ros:jade docker image and it works now.
