### ISSUE TITLE
swri_opencv_util Does not Build on ROS Farm

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#399]
I think this may be because of  amissing rosdep key for opencv 3.

See http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__swri_opencv_util__ubuntu_xenial_amd64__binary/12/console

**Comment by pjreed** [comment]
It appears that `swri_geometry_util` still has a `find_package(OpenCV 2 REQUIRED)`.  Also, both it and `swri_opencv_util`'s package.xml depend on `libopencv-dev` rather than `cv_bridge`.

**Comment by pjreed** [comment]
Fixed by #395.
