### ISSUE TITLE
swri_yaml_util Fails Current Version of Industrial CI

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#411]
I recently discovered that swri_yaml_util is failing CI where it previously was passing (see #410). Since swri_yaml_util hadn't changed, I deduced that Industrial CI had changed their CI scripts. It turns out that when ros-industrial/industrial_ci#116 started running all tests in docker, they set the source space in the docker image to read-only. This is a problem for swri_yaml_util, because it creates a file (version.h) in the source directory.

I'm inclined to say that Industrial CI's behavior (forcing read-only on the source directory) is correct here. Catkin builds are supposed to be out-of-source. We should fix swri_yaml_util.

**Comment by evenator** [comment]
@130s FYI

**Comment by 130s** [comment]
Yes, another user is affected and we're discussing at https://github.com/ros-industrial/industrial_ci/issues/122 and https://github.com/ros-industrial/industrial_ci/pull/123
CC @ipa-mdl

**Comment by ipa-mdl** [comment]
According to CMake conventions these generated files should be kept in `${PROJECT_BINARY_DIR}` or `${CMAKE_CURRENT_BINARY_DIR}` (this is somewhere within the build space)
For catkin-packages devel space is fine as well.
This way you can build the same src linked into different workspace without any collisions.
