### ISSUE TITLE
swri_transform_util handles "/wgs84" but not "wgs84"

### ISSUE THREAD

**Issue by pjreed** [swri-robotics/marti_common#444]
See swri-robotics/mapviz#478.  I would expect `swri_transform_util` to handle whatever its `wgs84_frame` is set to regardless of whether it has a slash in front of it or not.

**Comment by danielsnider** [comment]
This issue prompts the question, does it make sense to allow "utm" in addition to "/utm" as well? How about "/local_xy" too?

Relevent file: https://github.com/swri-robotics/marti_common/blob/indigo-devel/swri_transform_util/include/swri_transform_util/frames.h

**Comment by evenator** [comment]
👍 For adding support to the non-slash, but I don't think we should change the constants--that just creates confusion on the user end.

I recommend implementing a custom comparison function in `swri_transform_util` that does TF frame comparison and matches regardless of the leading slash. That way we can guarantee consistent behavior across the whole codebase, and I can think of other places I've had to compare TF frames that it would be useful.

**Comment by evenator** [comment]
`tf` uses `tf::strip_leading_slash()` before all comparisons for this reason. That might be the answer here as well. I still prefer the idea of implementing a comparison function, but that might just be because I wrote too much Java in my youth.

**Comment by pjreed** [comment]
While implementing something like `String.compareIgnoreLeadingSlash()` would make me happy, for the sake of consistency it's probably better to do it just like `tf` does it.
