### ISSUE TITLE
swri_image_util: A Nodelet to Perform Arbitary Perspective Transforms

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#445]
I need a nodelet that can apply an arbitrary perspective transformation, specified by a 3x3 transformation matrix. This is similar to what [image_proc/rectify](https://wiki.ros.org/image_proc#image_proc.2BAC8-diamondback.image_proc.2BAC8-rectify) does, but image_proce/rectify only works on calibrated cameras (if the k matrix is not filled, it refuses to process images, and if the distortion vector is not filled, it passes through images unchanged).

This node should take in a 3x3 transformation matrix as a parameter, a list of 9 floats, apply that transform to an incoming image using OpenCV, and publish the resulting image. There may be other parameters for cropping and interpolation options.

**Comment by pjreed** [comment]
[QMatrix4x4](https://doc.qt.io/qt-5/qmatrix4x4.html) might be able to do what you want.  It'd feel a little silly to import Qt just for that, but `swri_image_util` depends on Qt anyway...
