### ISSUE TITLE
swri_transform_util: initialize_origin.py does not set stamp

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#447]
In Indigo, when `initialize_origin.py` is run with a manual origin, it does not set `header.stamp` of the `gps_common/GpsFix` message it publishes.

**Comment by pjreed** [comment]
I'd recommend checking the `branch-consolidation` branch to see whether this affects newly-created NavSatFix messages as well.

**Comment by pjreed** [comment]
This was fixed back in the initialize_origin rewrite, so closing this issue.
