### ISSUE TITLE
Finish Branch Unification

### ISSUE THREAD

**Issue by evenator** [swri-robotics/marti_common#453]
- [x] Sync master branch with indigo-devel
- [x] Set master as the default branch
- [x] Update readme
- [x] Delete `jade-devel` (replace with tag)
- [x] Migrate SwRI's internal projects to the master branch (or to Debian installations)
- [x] Delete `kinetic-devel` (replace with tag)
- [x] Delete `indigo-devel` (replace with tag)

**Comment by pjreed** [comment]
MRs have been submitted in GitLab for the affected workspace files.

**Comment by pjreed** [comment]
I've submitted PRs to release `0.3.0` of `marti_common` into indigo, jade, kinetic, and lunar:

- ros/rosdistro#15312
- ros/rosdistro#15313
- ros/rosdistro#15315
- ros/rosdistro#15316

**Comment by pjreed** [comment]
PRs have been accepted, so I'll close this.
