### ISSUE TITLE
how to use this stack 

### ISSUE THREAD

**Issue by pzy2253999075** [swri-robotics/marti_common#539]
could someone tell me is there  some documentations about how to use this stack .

**Comment by daniel-dsouza** [comment]
Unfortunately there is no documentation for most of marti_common, and no plans to flesh it out in the future.

**Comment by matt-attack** [comment]
You can find a tiny bit of documentation here: https://github.com/swri-robotics/marti_common/blob/master/swri_roscpp/readme.md
