### ISSUE TITLE
Prevent segfault from swri::Subscriber during initial bagfile playback

### ISSUE THREAD

**Issue by jgassaway** [swri-robotics/marti_common#547]
When using a swri:Subscriber which is calculating msg latency diagnostics, a node will segfault when this set of operations is performed:
1. Start a new roscore
2. Set the rosparam /use_sim_time to true
3. Run the node with a swri::Subscriber
4. Start a bagfile (outputting clock) in paused mode ($ rosbag play --clock <some bag> --pause)

In this case, the node will immediately crash because of a std::runtime_error where "Duration is out of dual 32-bit range"

This appears to come from line 84 of swri_roscpp/include/swri_roscpp/subscriber_impl.h in the case where now is at time zero (sec: 0, nsec: 0), but stamp is at some non-zero time. Most likely, this is caused by receiving an initial message with a stamp before receiving the /clock msg that updates ros::Time::now().

**Comment by danthony06** [comment]
Fixed via https://github.com/swri-robotics/marti_common/pull/734
