### ISSUE TITLE
Topic Services not working on ROS2 (foxy)

### ISSUE THREAD

**Issue by dvmartin999** [swri-robotics/marti_common#601]
The swri-roscpp support for topic services under ROS2 (at least for foxy, but I'm pretty sure dashing as well) isn't working because of a change in message name generation.  The current python splitter expects <Service>Request.h and <Service>Response.h, but with ROS2, the IDL generator forces names into snake_case. The splitter needs to be updated accordingly.

**Comment by pjreed** [comment]
@matt-attack, do you have time to look at this?  If not, this might be a good issue for @danthony06.

**Comment by danthony06** [comment]
I can look at it.

**Comment by dvmartin999** [comment]
@danthony06 I've got a fix I'm working with now, should be a couple days before I can verify.  I'm happy to provide as-is, or push when it's ready.  Just let me know how you want to proceed.

**Comment by danthony06** [comment]
If you have a fix, I can work on verifying it.

**Comment by dvmartin999** [comment]
Can you add me as a contributor, then I can just push my branch.  Or would you prefer I send by email?

**Comment by danthony06** [comment]
Do you have the repo forked somewhere that I could branch off of?

**Comment by dvmartin999** [comment]
Ok - forked, pushed my changes to the fork, and PRed into your dashing branch.  Let me know if you have any questions or prefer a different workflow.

**Comment by pjreed** [comment]
Fixed by #604.
