### ISSUE TITLE
swri_transform_util [Foxy]: UtmTransformer silently doesn't initialize based on tf tree

### ISSUE THREAD

**Issue by jonselling** [swri-robotics/marti_common#632]
Depending on the value of the frame set in the local_xy_util (either through a "/local_xy_origin" message or a parameter), the UtmTransformer [will not initialize](https://github.com/swri-robotics/marti_common/blob/dashing-devel/swri_transform_util/src/utm_transformer.cpp#L146-L151). This was an issue when trying to set a frame_id with a leading "/". The tf2 buffer core code seems to be pretty consistent on [removing leading slashes](https://github.com/ros2/geometry2/blob/ros2/tf2/src/buffer_core.cpp#L204-L205)

I think this can be resolved with:

1. Adding an else statement with a RCLCPP_ERROR stating the frame was not in the tf buffer. Possibly printing all available frame.
2. Remove any leading slash in the [Handle Origin function](https://github.com/swri-robotics/marti_common/blob/dashing-devel/swri_transform_util/src/local_xy_util.cpp#L147-L179) for the LocalXyWgs84Util class. I believe this change is fine, since it seems like we assume that the frame_id is in the tf tree (which requires no leading slash).

**Comment by danthony06** [comment]
@jonselling https://github.com/swri-robotics/marti_common/pull/725 should implement both of your fixes.
