### ISSUE TITLE
swri_roscpp [Foxy]: TopicServiceClient spins node passed in during call

### ISSUE THREAD

**Issue by jonselling** [swri-robotics/marti_common#633]
When passing in a node to the topic service client, it will [spin the node](https://github.com/swri-robotics/marti_common/blob/dashing-devel/swri_roscpp/include/swri_roscpp/topic_service_client.h#L84-L123). This will conflict if we are trying to spin the node already externally, and this will cause an exception since the node is already added to an executor.

While it would be nice for the code to spin for you, it might be worthwhile to pass in a flag in the constructor if we want to disable the spinning ourselves.

As a side note, it might be good to make the interface a "rclcpp::Node::SharedPtr" to begin with if you are going to spin the node, instead of using a reference and then ".shared_from_this()".

**Comment by mboulet** [comment]
It may be worth considering a tf2-like model

**Comment by danthony06** [comment]
@jonselling sorry for the long delay on this. I'm trying to clear the backlog on a lot of our packages, and I'm starting in on this package. I think I can write the fix for this, but do you have a specific test case I could use to make sure my fix addresses your problem?

**Comment by jonselling** [comment]
I think a simple test case would be to construct a node that creates a TopicServiceClient and a timer on different callback groups, spins the node with a mutli-threaded spinner, and then call a service in that timer callback. A TopicServiceServer does need to be running from an external node.

Spinning the node may be a desirable option for someone (analogous to `spin_until_future_complete`) so maybe passing a bool in the constructor or "call" function could be a viable option.

**Comment by danthony06** [comment]
@jonselling I'm working on this, but I'm also trying to update it so it more closely matches the behavior of ROS2 services, which is taking a little more thought than I expected.

**Comment by jonselling** [comment]
Is that a requirement? Or do we want to preserve functionality of topic services in ROS1?

When you say match the functionality of ROS 2 services are you talking about making these calls asynchronous?

**Comment by danthony06** [comment]
My main concern is as written, we can hang forever waiting for the pub/sub
pair to become available. This seems a lot more likely in ROS 2, with the
focus on poor communication channels and fully distributed computing. I'm
working on adding a wait_for call in the system to mimic the ROS2 service
functionality.

**Comment by danthony06** [comment]
Okay, I'm going to test this tomorrow and work through the bugs:
https://github.com/swri-robotics/marti_common/compare/ros2-devel...danthony06:optional_spin?expand=1

**Comment by danthony06** [comment]
@jonselling I think this PR is going to fix this issue:
https://github.com/swri-robotics/marti_common/pull/672

**Comment by danthony06** [comment]
https://github.com/swri-robotics/marti_common/pull/672
