### ISSUE TITLE
swri_transform_util incompatible with proj 8

### ISSUE THREAD

**Issue by Tobias-Fischer** [swri-robotics/marti_common#642]
Hiya,

The (deprecated) `proj_api.h` has been removed from proj 8 onward. See https://proj.org/development/migration.html#api-migration

It would be great if you could update swri_transform_util for compatibility with proj 8 :).

We discovered this in RoboStack: https://github.com/robostack/ros-noetic

**Comment by danthony06** [comment]
Thanks, I'm looking at how to solve this as part of our Humble update, and I think the fix will be backported to Noetic.

**Comment by danthony06** [comment]
Fixed via https://github.com/swri-robotics/marti_common/pull/733.
