### ISSUE TITLE
Initialize Origin Timer Unneccessary

### ISSUE THREAD

**Issue by agyoungs** [swri-robotics/marti_common#662]
I don't believe the local_xy_origin needs to be published at a rate if it is a latched (transient local in ROS2) topic. Unless the origin can change, this doesn't seem needed. If the origin can change at runtime I think it will could break parts of the system expecting the map to WGS84 transform to remain consistent.

https://github.com/swri-robotics/marti_common/blob/d88eded3f9e573a28570ca590681453d62004e99/swri_transform_util/src/swri_transform_util/origin_manager.py#L314

**Comment by rjb0026** [comment]
@danthony06 Was this issue fully addressed by #667? Can it be closed out?

**Comment by danthony06** [comment]
I think so
